language: objective-c
osx_image: xcode7.2

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - IOS_FRAMEWORK_SCHEME="SwiftEncoderKit-iOS"
    - OSX_FRAMEWORK_SCHEME="SwiftEncoderKit-Mac"
#    - TVOS_FRAMEWORK_SCHEME="SwiftEncoderKit-tvOS"
    - IOS_SDK=iphonesimulator9.2
    - OSX_SDK=macosx10.11
#    - TVOS_SDK=appletvsimulator9.0    
  matrix:
    - DESTINATION="OS=9.0,name=iPhone 4S"       SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" 
    - DESTINATION="OS=9.0,name=iPhone 5S"       SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=9.1,name=iPhone 6"        SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=9.2,name=iPhone 6s Plus"  SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="arch=x86_64"                 SCHEME="$OSX_FRAMEWORK_SCHEME" SDK="$OSX_SDK"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project SwiftEncoderKit.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - xcodebuild -project SwiftEncoderKit.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c

notifications:
  email: false